name: Metadata Record Correction
description: Issue template for submitting metadata record corrections.
title: "[Metadata Correction]: "
labels: ["correction-submitted", "review-pending"]

body:
  - type: markdown
    attributes:
      value: |
        This template is for submitting corrections to metadata records. Please provide detailed information to help us process your correction efficiently.

  - type: dropdown
    id: correctionScope
    attributes:
      label: Correction Scope
      description: Does the correction apply to a specific record, some of the records, or all of the records for which the metadata value is present for the metadata field?
      options:
        - "specific record - e.g. it's only wrong in this record, but seems right elsewhere"
        - "some records - e.g. it's seems to be wrong for a number of records, but right for others"
        - "most or all records - e.g. it seems to be wrong for most or all of the records."
    validations:
      required: true

  - type: input
    id: metadataRecordID
    attributes:
      label: Metadata Record Identifier
      description: If the correction is for a specific record, provide the unique identifier of the metadata record you are referring to.
      placeholder: ex. ZENODO_4745839
    validations:
      required: false

  - type: dropdown
    id: metadataField
    attributes:
      label: metadata field
      description: The metadata field for which a correction is needed
      options:
        - "species"
        - "infectiousAgent"
        - "healthCondition"
        - "conditionsOfAccess"
        - "topicCategory"
        - "measurementTechnique"
        - "variableMeasured"
        - "other"
    validations:
      required: true  

  - type: input
    id: otherField
    attributes:
      label: Other metadata field
      description: If you selected `other` in the previous drop down, please specify the metadata field in need of correction.
      placeholder: ex. funding
    validations:
      required: false

  - type: input
    id: termInQuestion
    attributes:
      label: Term in Question
      description: Specify the term that is incorrectly mapped in the metadata.
      placeholder: ex. Nevada, binary
    validations:
      required: true

  - type: textarea
    id: errorDescription
    attributes:
      label: Error Description
      description: Describe the error in the metadata record and the context of the misuse.
      placeholder: "ex. The term 'Nevada' is mapped as a species, but in this context, it refers to a state."
    validations:
      required: true

  - type: dropdown
    id: proposedCorrectionType
    attributes:
      label: Proposed Correction Type
      description: Select the type of corrective action to be taken
      options:
        - "replace value"
        - "remove value"
        - "append value"
    validations:
      required: true

  - type: textarea
    id: proposedCorrection
    attributes:
      label: Proposed Correction
      description: Provide your proposed correction in detail, including any specific action to be taken. Include a URI if you are proposing to append or replace a term.
      placeholder: "ex. Replace 'Mus musculus' in the species field with 'Homo sapiens' for record ZENODO_4745839. The correct species is a human cell line, not a mouse model. UniProt Taxonomy URL: https://www.uniprot.org/taxonomy/9606"
    validations:
      required: true

  - type: textarea
    id: correctionEvidence
    attributes:
      label: Evidence or Reasoning for the Correction
      description: Provide any evidence or reasoning that supports your correction.
      placeholder: "ex. The correct author name is mentioned in the associated publication DOI: 10.5281/zenodo.4745839"
    validations:
      required: false

  - type: input
    id: additionalReferences
    attributes:
      label: Additional References
      description: If applicable, provide any additional references or links related to this correction.
      placeholder: ex. https://example.com/additional-info
    validations:
      required: false

  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency
      description: Indicate if this correction is urgent.      
      options:
        - label: This is an urgent correction
    validations:
      required: false

  - type: markdown
    attributes:
      value: |        
        Thank you for contributing to the accuracy and integrity of our metadata records. We will review your submission and get back to you as soon as possible.
